### ISSUE TITLE
Explore issues with CSS libraries @import'ing fonts

### ISSUE THREAD

**Issue by addyosmani** [addyosmani/critical-css-weather-app#2]
See: https://github.com/addyosmani/critical-css-weather-app/blob/gh-pages/output/critical/index.html#L5

I believe this is being caused by Penthouse stripping the font rules. Will explore further.

**Comment by pocketjoso** [comment]
This is related to @import rules, which were not previously handled by Penthouse.

It was fixed in v0.2.3.

**Comment by pocketjoso** [comment]
Actually I had missed to handle **@charset** rules, so it was still broken by the last version.

Fixed today in v.0.2.5. (Now handling all @-rules properly)

**Comment by addyosmani** [comment]
Thanks for the updates and staying on top if this issue. I'm happy for us to bump up to latest. Will retest locally and get it updated.

**Comment by addyosmani** [comment]
Updated to latest. Thanks a lot @pocketjoso!
